<!DOCTYPE html>
<html lang="en">

<head>
    <title>KSEB LOGIN</title>
    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 10]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="#">
    <meta name="keywords" content="Admin , Responsive, Landing, Bootstrap, App, Template, Mobile, iOS, Android, apple, creative app">
    <meta name="author" content="#">
    <!-- Favicon icon -->
    <link rel="icon" href="<?php echo base_url(); ?>favicon.png" type="image/x-icon">
    <!-- Google font--><link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/web_user/files\bower_components\bootstrap\css\bootstrap.min.css">
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/web_user/files\assets\icon\themify-icons\themify-icons.css">
    <!-- ico font -->
    <link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/web_user/files\assets\icon\icofont\css\icofont.css">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/web_user/files\assets\css\style.css">
</head>
<style>
.login-block{

	background: #f7f7f7 !important;
}
.card-block {
    box-shadow: 0 0 2px #9c9c9c;
}

.scale-up-center {
	-webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0.5s both;
	        animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0.5s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-12-30 18:15:1
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}


</style>
<body class="fix-menu">
    <!-- Pre-loader start -->
    <div class="theme-loader">
        <div class="ball-scale">
            <div class='contain'>
                <div class="ring"><div class="frame"></div></div>
                <div class="ring"><div class="frame"></div></div>
                <div class="ring"><div class="frame"></div></div>
                <div class="ring"><div class="frame"></div></div>
                <div class="ring"><div class="frame"></div></div>
                <div class="ring"><div class="frame"></div></div>
                <div class="ring"><div class="frame"></div></div>
                <div class="ring"><div class="frame"></div></div>
                <div class="ring"><div class="frame"></div></div>
                <div class="ring"><div class="frame"></div></div>
            </div>
        </div>
    </div>
    <!-- Pre-loader end -->

    <section class="login-block">
        <!-- Container-fluid starts -->
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <!-- Authentication card start -->
                    <?php
                    $atributes=array('class'=>'md-float-material form-material','id'=>'frm', 'name'=>'frm' ,'autocomplete'=>'off');
                      echo form_open('home/admin_login',$atributes);
                     ?>
                            <div class="text-center scale-up-center ">
                                <img src="<?php echo base_url(); ?>assets/web_user/files\assets\images\logo.png" alt="logo.png" style="width:20%;">
                            </div>
                            <div class="auth-box card">
                                <div class="card-block scale-up-center">
                                    <div class="row m-b-20">
                                        <div class="col-md-12">
                                            <h3 class="text-center">Forgot Password?</h3>
                                        </div>
                                    </div>
                                    <div class="form-group form-primary" id="email_block">
                                      <label>Enter your email id</label>
                                        <input type="email" name="email" id="email" class="form-control" required="" placeholder="Enter your registered email id" autocomplete="off">
                                        <span class="form-bar"></span>
                                    </div>

                                    <div id="pwd_block" style="display:none">
                                      <div class="form-group form-primary" id="email_block">
                                        <label>New Password</label>
                                          <input type="password" name="n_password" id="n_password" class="form-control" required="" placeholder="New password" autocomplete="off">
                                        </div>
                                        <div class="form-group form-primary" id="email_block">
                                          <label>Confirm Password</label>
                                            <input type="password" name="c_password" id="c_password" class="form-control" required="" placeholder="Confirm password" autocomplete="off">
                                        </div>
                                        <div class="form-group form-primary" id="email_block">
                                          <label>OTP</label>
                                            <input type="number" name="otp" id="otp" class="form-control" required="" placeholder="OTP you received in mail" autocomplete="off">
                                        </div>
                                        <span class="form-bar"></span>
                                    </div>

                                    <div class="row m-t-30">
                                        <div class="col-md-12" id="gtop">
                                            <button type="button" onclick="checkuser()" id="btn" class="btn btn-primary btn-md btn-block waves-effect waves-light text-center m-b-20">GET OTP</button>
                                        </div>
                                        <div class="col-md-12" id="chgpwd" style="display:none">
                                            <button type="button" onclick="changepwd()" id="btn" class="btn btn-info btn-md btn-block waves-effect waves-light text-center m-b-20">RESET PASSWORD</button>
                                        </div>
                                    </div>
                                    <span style="color:red" id="error">
                                         <?php
                                      $er= $this->session->flashdata("error");
                                     echo $this->session->flashdata("error");
                                      if($er)
                                      {
                                      //  print '<script>alert("error")</script>';
                                      }
                                      ?>
                                    </span>
                                    <hr>

                                    <div class="row">
                                        <div class="col-md-10">
                                            <!-- <p class="text-inverse text-left m-b-0">Developed By:</p> -->
                                            <p class="text-inverse text-left"><a href="index-1.htm"><b class="f-w-600">Netroxe IT Solutions Pvt.Ltd.</b></a></p>
                                        </div>
                                        <div class="col-md-2">
                                            <img src="<?php echo base_url(); ?>assets/web_user/files\assets\images\auth\Logo-small-bottom.png" alt="small-logo.png" style="width:100%;">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- end of form -->
                </div>
                <!-- end of col-sm-12 -->
            </div>
            <!-- end of row -->
        </div>
        <!-- end of container-fluid -->
    </section>

    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\jquery\js\jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\jquery-ui\js\jquery-ui.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\popper.js\js\popper.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\bootstrap\js\bootstrap.min.js"></script>
    <!-- jquery slimscroll js -->
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\jquery-slimscroll\js\jquery.slimscroll.js"></script>
    <!-- modernizr js -->
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\modernizr\js\modernizr.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\modernizr\js\css-scrollbars.js"></script>
    <!-- i18next.min.js -->
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\i18next\js\i18next.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\i18next-xhr-backend\js\i18nextXHRBackend.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\i18next-browser-languagedetector\js\i18nextBrowserLanguageDetector.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\bower_components\jquery-i18next\js\jquery-i18next.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>assets/web_user/files\assets\js\common-pages.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->

<script>
$(document).ready(function(){
  $("input").attr("autocomplete", "off");
});
function changepwd()
{
  otp=$("#otp").val();
  n_password=$("#n_password").val();
  c_password=$("#c_password").val();

  if(otp>0 && n_password!="" && c_password!="")
  {
      if(n_password==c_password)
      {
          keyval={otp:otp,n_password:n_password,c_password:c_password,type:2}
        $.ajax({
           type: "POST",
           url: '<?php echo base_url() ?>home/forgotpaswrdManage',
           data: keyval ,
           success: function(result){
                if(result==1)
                {
                    $("#error").html("Yor password has been reset, Now try login");
                    setTimeout(function() {
                          window.open("<?php echo base_url(); ?>",'_self');
                      }, 3000);
                }
                else {
                    $("#error").html(result);
                }
             }
        });
      }
      else {
        $("#error").html("New password and confirm an password do not match");
      }
  }
  else {
      $("#error").html("You must fill all coloumns");
  }

}
function checkuser()
{
  email=$("#email").val();

  if(email)
  {
    $("#btn").html("Please wait...");
    $("#btn").attr("disabled",true);
    keyval={email:email,type:1}
      $.ajax({
         type: "POST",
         url: '<?php echo base_url() ?>home/forgotpaswrdManage',
         data: keyval ,
         success: function(result){
              if(result==1)
              {
                  $("#email_block").hide();
                  $("#gtop").hide();
                  $("#chgpwd").show();
                  $("#pwd_block").show();
                  $("#error").html("An otp has been sent to "+email+" Please enter it to reset your password");
              }
              else {
                $("#error").html(result);
              }

              $("#btn").html("GET OTP");
              $("#btn").attr("disabled",false);
           }
      });
  }
  else {
    $("#error").html("You must enter your email id");

  }
}
</script>
</body>

</html>
